INSERT INTO USERS VALUES('77778888','{noop}12345',TRUE);
INSERT INTO USERS VALUES('admin','{noop}secret',TRUE);

INSERT INTO AUTHORITIES VALUES('77778888','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('77778888','ROLE_EDITOR');
INSERT INTO AUTHORITIES VALUES('admin','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('admin','ROLE_EDITOR');
INSERT INTO AUTHORITIES VALUES('admin','ROLE_ADMIN');   